# Generated by Django 5.1.7 on 2025-03-24 16:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='service.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='users',
            field=models.ManyToManyField(related_name='assigned_tasks', to='service.users'),
        ),
    ]
